name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release
    - name: make
      run: make
